docker_build: &docker_build
  image: plugins/docker
  registry: docker-dev.core.rcsops.com
  repo: docker-dev.core.rcsops.com/${DRONE_REPO_NAME}
  dockerfile: docker-image/v0.12/alpine-kafka/Dockerfile

proxy_environment: &proxy_environment
  environment:
    - http_proxy=http://10.131.236.9:3128
    - https_proxy=http://10.131.236.9:3128
    - no_proxy=localhost,127.0.0.1,docker-dev.core.rcsops.com

pipeline:
  verify:
    <<: *docker_build
    <<: *proxy_environment
    dry_run: true
    when:
      event: pull_request

  publish:
    <<: *docker_build
    <<: *proxy_environment
    secrets:
      - docker_username
      - docker_password
    commands:
      - make image DOCKERFILE=v0.12/alpine-kafka
      - docker tag IMAGE[:TAG] [REGISTRYHOST/][USERNAME/]NAME[:TAG]
      - docker tag fluent/fluentd-kubernetes:stable-kafka docker-dev.core/rcsops.com/${DRONE_REPO_NAME}/fluent/fluentd-kubernetes:stable-kafka
      - docker push docker-dev.core/rcsops.com/${DRONE_REPO_NAME}/fluent/fluentd-kubernetes:stable-kafka
    when:
      event:
        - tag
        - push
      branch:
        - master
        - refs/tags/*