pyrex_environment: &pyrex_environment
  image: docker-dev.core.rcsops.com/pyrex-runner:0.8.2
  secrets:
    - docker_username
    - docker_password

proxy_environment: &proxy_environment
  environment:
    - http_proxy=http://10.131.236.9:3128
    - https_proxy=http://10.131.236.9:3128
    - no_proxy=localhost,127.0.0.1,docker-dev.core.rcsops.com

pipeline:
  verify:
    <<: *pyrex_environment
    <<: *proxy_environment
    commands:
      - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - docker build -t fluent/fluentd-kubernetes:v0.12.33-kafka docker-image/v0.12/alpine-kafka
    when:
      event: pull_request

  publish:
    <<: *pyrex_environment
    <<: *proxy_environment
    commands:
      - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - docker tag fluent/fluentd-kubernetes:v0.12.33-kafka fluent/fluentd-kubernetes:v0.12.33-kafka
      - docker push fluent/fluentd-kubernetes:v0.12.33-kafka
    when:
      event:
        - tag
        - push
      branch:
        - master
        - refs/tags/*